//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomewhereDesktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SomewhereDesktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Markdown Cheatsheet is Authored by Adam Pritchard on [Github](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).
        ///
        ///This is intended as a quick reference and showcase. For more complete info, see [John Gruber&apos;s original spec](http://daringfireball.net/projects/markdown/) and the [Github-flavored Markdown info page](http://github.github.com/github-flavored-markdown/).
        ///
        ///Note that there is also a [Cheatsheet specific to Markdown Here](./Markdown-Here-Cheatsheet) if that&apos;s what you&apos;re loo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MarkdownReference {
            get {
                return ResourceManager.GetString("MarkdownReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Mouse Operations
        ///
        ///1. `Double Click` on **Invetory panel** list view item can open it using default system program.
        ///2. Double Click on file:
        ///3. Right click on file:
        ///4. Right click on home: 
        ///5. (Planned) Win32 on filename and new button for file and folder win33 context menu
        ///
        ///# Window
        ///
        ///* `F11`  Maximize Somewhere Desktop window
        ///* `F12`  Show Shortcuts
        ///* `` Ctrl+\` ``: Hide Somewhere Desktop window 
        ///* `ESC`:  Hide Somewhere Desktop window (same as `` Ctrl+\` ``)
        ///
        ///# Panels
        ///
        ///* `Ctrl+1`: Show I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShortcutsDocument {
            get {
                return ResourceManager.GetString("ShortcutsDocument", resourceCulture);
            }
        }
    }
}
